# Use vi keys in copy mode
setw -g mode-keys vi

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Setup 'y' to yank (copy) to system clipboard
# Must have xclip installed by the system package manager
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -sel clipboard -i"

# Uncomment to open new windows in the current directory
#bind c new-window -c "#{pane_current_path}"

# Open new panes (splits) in the current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Set the default terminal terminfo to support 256 colors
set -g default-terminal "screen-256color"

# Tell tmux to pass through TrueColor / RGB sequences from your host terminal
# (Replace xterm-256color with your actual host terminal $TERM if it is different)
set-option -sa terminal-overrides ",xterm-256color:Tc"
